version: 2.1

defaults: &defaults
  docker:
    - image: prettyfuntherapy/node-10-x-standard-ci
  working_directory: /home/circleci/server-plugin-tag-cloud-watch-logs

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: |
            npm run npmrc
            npm --no-optional install
      - save_cache:
          key: node-module-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: "/home/circleci"
          paths:
            - "server-plugin-tag-cloud-watch-logs"
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: "/home/circleci"
      - restore_cache:
          keys:
            - prod-node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: prod-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - "dist/node_modules"
      - persist_to_workspace:
          root: "/home/circleci"
          paths:
            -  server-plugin-tag-cloud-watch-logs/dist

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Authenticate with registry
          command: npm run npmrc
      - run:
          name: Publish package
          command: npm --unsafe-perm --access public publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              only:
                - master
      - publish-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - publish-approval
